global:
  domain: "localdomain"
  certificateName: # opcional, puede quedar vacío para usar los secretName específicos

api-subscription:
  enabled: true
  ingress:
    enabled: true
    host: "api-subscription"
    tls:
      enabled: true
      secretName: api-subscription-tls

web-subscription:
  enabled: true
  ingress:
    enabled: true
    host: "web-subscription"
    tls:
      enabled: true
      secretName: web-subscription-tls

api-subscription-worker:
  enabled: true