apiVersion: v2
name: origin
version: 1.2.4
description: CreditForce Origin Helm chart for Kubernetes 
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://images8.webydo.com/96/9628253/3958/F6AD13C0-3367-06E4-3434-7E46130909F9.png
appVersion: "0.0.1"

dependencies:

  - name: api-origin
    version: 1.1.5
    repository: "file://../api-origin/"
    condition: api-origin.enabled

  - name: api-store
    version: 1.1.5
    repository: "file://../api-store/"
    condition: api-store.enabled

  - name: web-origin
    version: 1.1.9
    repository: "file://../web-origin/"
    condition: web-origin.enabled
