apiVersion: v2
description: Rules Manager chart for Kubernetes
name: rules-manager
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 0.1.271
appVersion: "0.0.1"
