apiVersion: v2
name: core
version: 0.0.3
description: CreditForce Core Helm chart for Kubernetes 
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://www.credit-force.com/wp-content/uploads/2021/04/FAVICON-300x300.png
appVersion: "0.0.1"

dependencies:

  - name: api-creditengine
    version: 0.1.262
    repository: "file://../api-creditengine/"
    condition: api-creditengine.enabled

  - name: web-core
    version: 0.0.3
    repository: "file://../web-core/"
    condition: web-core.enabled
