apiVersion: v2
description: API CrediEngine chart for Kubernetes
name: api-creditengine
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 0.0.44
appVersion: "0.0.1"
