apiVersion: v2
description: API Workflow Interaction chart for Kubernetes
name: workflow-api-interaction
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 0.0.62
appVersion: "0.0.1"
