apiVersion: v2
name: notification-hub
version: 0.0.1
description: Notification hub Security Helm chart for Kubernetes 
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://images8.webydo.com/96/9628253/3958/F6AD13C0-3367-06E4-3434-7E46130909F9.png
appVersion: "1.0.2"

dependencies:

  - name: api-notification-hub
    version: 1.0.4
    repository: "file://../api-notification-hub/"
    condition: api-notification-hub.enabled

  - name: engine-notification-hub
    version: 1.0.4
    repository: "file://../engine-notification-hub/"
    condition: engine-notification-hub.enabled
