apiVersion: v2
name: rules
version: 0.1.237
description: CreditForce Rules Helm chart for Kubernetes 
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
appVersion: "0.0.1"

dependencies:

  - name: api-rules
    version: 0.1.237
    repository: "file://../api-rules/"
    condition: api-rules.enabled

  - name: api-rules-engine
    version: 0.1.237
    repository: "file://../api-rules-engine/"
    condition: api-rules-engine.enabled

  - name: rules-manager
    version: 0.1.237
    repository: "file://../rules-manager/"
    condition: rules-manager-engine.enabled  
