apiVersion: v2
description: api-creditcollection chart for Kubernetes
name: api-creditcollection
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 0.1.268
appVersion: "0.0.1"
