apiVersion: v2
name: base
version: 0.0.27
description: Credit Engine Base Helm chart for Kubernetes
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
appVersion: "0.0.3"

dependencies:

  - name: creditflow
    version: 0.0.27
    repository: "https://creditforce.github.io/helm-chart"
    condition: creditflow.enabled

  - name: api-notification
    version: 0.0.27
    repository: "https://creditforce.github.io/helm-chart"
    condition: api-notification.enabled

  - name: api-notification-engine
    version: 0.0.27
    repository: "https://creditforce.github.io/helm-chart"
    condition: api-notification-engine.enabled

  - name: api-security
    version: 0.0.27
    repository: "https://creditforce.github.io/helm-chart"
    condition: api-security.enabled

  - name: security-manager
    version: 0.0.27
    repository: "https://creditforce.github.io/helm-chart"
    condition: security-manager.enabled
