apiVersion: v2
description: API Workflow Admin chart for Kubernetes
name: workflow-admin
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
version: 0.1.170
appVersion: "0.0.1"
