apiVersion: v2
name: store
version: 0.0.39
description: CreditForce Store Helm chart for Kubernetes
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
appVersion: "0.0.1"

dependencies:

  - name: api-creditstore
    version: 0.0.37
    repository: "https://creditforce.github.io/helm-chart"
    condition: api-creditstore.enabled

  - name: creditstore
    version: 0.0.37
    repository: "https://creditforce.github.io/helm-chart"
    condition: creditstore.enabled  
