apiVersion: v2
name: store
version: 0.0.45
description: CreditForce Store Helm chart for Kubernetes 
sources:
  - https://creditforce.github.io/helm-chart/
icon:  https://avatars.githubusercontent.com/u/66394013
appVersion: "0.0.1"

dependencies:

  - name: api-creditstore
    version: 0.0.45
    repository: "file://../api-creditstore/"
    condition: api-creditstore.enabled

  - name: creditstore
    version: 0.0.45
    repository: "file://../creditstore/"
    condition: creditstore.enabled  
