name: pull_request

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Helm Lint Chart
      run: |
          helm version
          for chrt in api-creditcollection \
                      api-creditengine \
                      api-creditorigination \
                      api-creditstore \
                      api-notification \
                      api-notification-engine \
                      api-rules \
                      api-rules-engine \
                      api-security \
                      creditcollection \
                      creditflow \
                      creditstore \
                      customerservice \
                      origination-manager \
                      productmodeler \
                      rules-manager \
                      security-manager \
                      workflow-admin \
                      workflow-api-admin \
                      workflow-api-auth \
                      workflow-api-dashboard \
                      workflow-api-designer \
                      workflow-api-engine \
                      workflow-api-scripts \
                      workflow-api-interaction \
                      workflow-base-web \
                      workflow-dashboard \
                      workflow-dashboard-simulator \
                      web-core \
                      api-core
          do
            echo -e "\nPacking: $chrt..."
            helm lint charts/$chrt
          done
      shell: bash   
 
