name: pull_request

on: [pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Heml Lint Chart
      run: |
          for d in charts/*/ ; do
            helm dependency update $d
            helm lint $d
          done
      shell: bash   
 
