name: cf-chart-release

on: [pull_request]

jobs:
  cf_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run index.sh script
      run: |
         chmod +x ./index.sh
         ./index.sh
      shell: bash

