name: cf-chart-release

on: [pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Helm
      run: |
         wget https://get.helm.sh/helm-v3.10.1-linux-amd64.tar.gz
         tar -zxf helm-v3.10.1-linux-amd64.tar.gz
      shell: bash
    - name: Install Helm Chart Releaser
      run: |
         wget https://github.com/helm/chart-releaser/releases/download/v1.4.1/chart-releaser_1.4.1_linux_amd64.tar.gz
         tar -zxf chart-releaser_1.4.1_linux_amd64.tar.gz
         ls -la
      shell: bash
    - name: Build Charts..
      run: |
          for chrt in api-creditcollection \
                      api-creditengine \
                      api-creditorigination \
                      api-creditstore \
                      api-notification \
                      api-notification-engine \
                      api-rules \
                      api-rules-engine \
                      api-security \
                      creditcollection \
                      creditflow \
                      creditstore \
                      customerservice \
                      origination-manager \
                      productmodeler \
                      rules-manager \
                      security-manager \
                      workflow-admin \
                      workflow-api-admin \
                      workflow-api-auth \
                      workflow-api-dashboard \
                      workflow-api-designer \
                      workflow-api-interaction \
                      workflow-base-web \
                      workflow-dashboard \
                      workflow-dashboard-simulator
          do
            echo -e "\nPROCESSING: $chrt..."
            helm lint charts/$chrt
            helm package charts/$chrt --destination .deploy
          done
      shell: bash
    - name: Upload Charts...
      run: |
          ./cr upload -o creditforce -r helm-chart -p .deploy --skip-existing -t $GITHUB_TOKEN
      shell: bash
    - uses: actions/checkout@v3
    - name: Build Packages..
      run: |
          helm repo add creditforce https://creditforce.github.io/helm-chart/ 
          for pckg in base \
                      collection \
                      origination \
                      portfolio \
                      rules \
                      store \
                      workflow
          do
            echo -e "\nPROCESSING: $pckg..."
            helm dependency update charts/$pckg
            helm package charts/$pckg --destination .deploy
          done
    - name: Upload Packages...
      run: |
        ./cr upload -o creditforce -r helm-chart -p .deploy --skip-existing -t $GHP_TOKEN
        ./cr index -i ./index.yaml -p .deploy --owner creditforce --git-repo helm-chart -t $GHP_TOKEN
        # git add index.yaml
        # git commit -am"Update Helm chart repo index with new packages"
        # git push
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
